
<?php if($this->user): ?>
    <form method="post" action="addFabrica">
        <div class="mb-3">
                <label for="nombre" class="form-label">
                    Nombre:
                </label>
                <input name="nombre" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="pais" class="form-label">
                    Pais:
                </label>
                <input name="pais" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="importador" class="form-label">
                    Importador:
                </label>
                <input name="importador" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="cantidad" class="form-label">
                    Stock:
                </label>
                <input name="cantidad" type="text" class="form-control" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
<?php endif;?>

