
<?php require './plantillas/layouts/header.phtml';?>


    <?php if(isset($fabrica)): ?>
        <h1> <?=$fabrica->nombre?> </h1>
        <p>Pais: <?=$fabrica->pais ?></p>
        <p>Importador: <?=$fabrica->importador?> </p>
        <p>Cantidad: <?=$fabrica->cantidad?> </p>
        <a href=" <?= BASE_URL ?>">Volver</a>
    <?php endif; ?>


   <?php if(isset($models)):?> 
        <ul>
            <?php foreach($models as $modelo):?>
                <li> <?=$modelo->nombre ?> </li> 
                <a href="detallesmodelo/<?=$modelo->id_zapatilla ?>">Ver mas</a>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
<?php require './plantillas/layouts/footer.phtml'; ?>