<h1>Editar Fábrica</h1>

<form action="update" method="post">
    <input type="hidden" name="id" value="<?=$fabrica->id;?>">
    
    <!-- Otros campos del formulario -->
    <input type="text" name="nombre" value="<?=$fabrica->nombre;?>" placeholder="Ingrese el nombre de la fábrica">
    <input type="text" name="importador" value="<?=$fabrica->importador;?>" placeholder="Ingrese el importador"> 
    <input type="text" name="pais" value="<?=$fabrica->pais;?>" placeholder="Ingrese el país"> 
    <input type="number" name="cantidad" value="<?=$fabrica->cantidad;?>" placeholder="Ingrese la cantidad"> 
    
    <button type="submit">EDITAR</button>
</form>