     <ul class="list-group">
        <?php if(isset($fabricas)): ?>
            <?php foreach($fabricas as $fabrica): ?>
                <li class="list-group-item item-fabrica d-flex justify-content-between align-items-center">
                    <span>
                        <?=$fabrica->nombre; ?>
                    </span>
                    <span>
                        <a href="detallesfabrica/<?=$fabrica->id;?>" class="btn btn-success btn-sm text-white">Ver más</a>
                    </span>
                </li>
            <?php endforeach; ?>
        <?php endif; ?>
    </ul>
    
    <?php if($this->user): ?> 
        <div class="text-center mt-3">
            <a href="showAddFabrica/" class="btn btn-primary">Hacer cambios</a>
        </div>
        <?php endif; ?>
