<?php require './plantillas/layouts/header.phtml'; ?>

<?php require './plantillas/layouts/tituloFabricas.phtml'; ?>

<?php require './plantillas/addfabrica.phtml'; ?>

<br>

<ul class="list-group">
    <?php if(isset($fabricas)): ?>
        <?php foreach($fabricas as $fabrica): ?>
            <li class="list-group-item item-fabrica d-flex justify-content-between align-items-center">
                <span>
                    <b><?=$fabrica->nombre; ?></b>
                </span>
                <span class="actions">
                    <button type="button" class="btn btn-success btn-sm">
                        <a href="detallesfabrica/<?=$fabrica->id;?>" class="text-white">Ver más</a>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ml-2">
                        <a href="deleteFab/<?=$fabrica->id;?>" class="text-white">Eliminar</a>
                    </button>
                    <button type="button" class="btn btn-warning btn-sm ml-2">
                        <a href="showEditFabrica/<?=$fabrica->id;?>" class="text-white">Editar</a>
                    </button>
                </span>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<?php require './plantillas/layouts/footer.phtml'; ?>