<?php require './plantillas/layouts/header.phtml'; ?>

<?php require './plantillas/addfabrica.phtml';?>

<ul class="list-group">
    <?php if(isset($fabricas)): ?>
        <?php foreach($fabricas as $fabrica): ?>
            <li class= "list-group-item item-fabrica">
                <span>
                    <b><?=$fabrica->nombre; ?></b>
                </span>
                <span class="actions">
                    <button type="submit" class="btn">
                        <a href="detallesfabrica/<?=$fabrica->id;?>">Ver mas</a>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ml-2">
                        <a href="delete/<?=$fabrica->id;?>" class="text-white">Eliminar</a>
                    </button>
                </span>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<?php require './plantillas/layouts/footer.phtml'; ?>